import {
    iconAlert,
    iconAPI,
    iconAuthKeyhole,
    iconBook,
    iconBraces,
    iconCloud,
    iconCombined,
    iconConsole,
    iconDatabase,
    iconDownload,
    iconFunction,
    iconHelp,
    iconHome,
    iconInfo,
    iconList,
    iconNamespace,
    iconPlus,
    iconQuery,
    iconServer,
    iconTransfer,
} from "@surrealdb/ui";

export const SECTION_ICONS = new Map([
    ["api", iconAPI],
    ["auth", iconAuthKeyhole],
    ["book", iconBook],
    ["braces", iconBraces],
    ["cli", iconConsole],
    ["cloud", iconCloud],
    ["combined", iconCombined],
    ["database", iconDatabase],
    ["download", iconDownload],
    ["error", iconAlert],
    ["function", iconFunction],
    ["help", iconHelp],
    ["home", iconHome],
    ["info", iconInfo],
    ["language", iconConsole],
    ["list", iconList],
    ["namespace", iconNamespace],
    ["plus", iconPlus],
    ["query", iconQuery],
    ["server", iconServer],
    ["server", iconServer],
    ["support", iconHelp],
    ["transfer", iconTransfer],
] as const);

export const SECTION_ICONS_NAMES = Array.from(SECTION_ICONS.keys());
export type SectionIconName = (typeof SECTION_ICONS_NAMES)[number];
