import {
    iconAccountSecure,
    iconAlert,
    iconAPI,
    iconAtom,
    iconAuthKeyhole,
    iconBook,
    iconBraces,
    iconBusiness,
    iconChart,
    iconChat,
    iconCheck,
    iconClock,
    iconCloud,
    iconCog,
    iconCombined,
    iconConsole,
    iconDatabase,
    iconDistributedStorage,
    iconDownload,
    iconFile,
    iconFlag,
    iconFunction,
    iconGraphql,
    iconHammer,
    iconHelp,
    iconHistory,
    iconHome,
    iconIndex,
    iconInfo,
    iconIntegration,
    iconKey,
    iconLangDotNet,
    iconLangGo,
    iconLangJava,
    iconLangJavaScript,
    iconLangKotlin,
    iconLangMojo,
    iconLangPHP,
    iconLangPython,
    iconLangRust,
    iconLangSwift,
    iconList,
    iconLive,
    iconMarker,
    iconMCP,
    iconMemory,
    iconModel,
    iconNamespace,
    iconPackageClosed,
    iconPlugin,
    iconPlus,
    iconQuery,
    iconRelation,
    iconSearch,
    iconServer,
    iconSidekick,
    iconSpectron,
    iconSurreal,
    iconSurrealist,
    iconTable,
    iconText,
    iconTransfer,
    iconUniversity,
    iconVariable,
    iconVideo,
    iconWrench,
} from "@surrealdb/ui";

export const SECTION_ICONS = new Map([
    ["account", iconAccountSecure],
    ["api", iconAPI],
    ["atom", iconAtom],
    ["auth", iconAuthKeyhole],
    ["book", iconBook],
    ["braces", iconBraces],
    ["business", iconBusiness],
    ["chart", iconChart],
    ["chat", iconChat],
    ["check", iconCheck],
    ["cli", iconConsole],
    ["clock", iconClock],
    ["cloud", iconCloud],
    ["cog", iconCog],
    ["combined", iconCombined],
    ["database", iconDatabase],
    ["dotnet", iconLangDotNet],
    ["download", iconDownload],
    ["error", iconAlert],
    ["file", iconFile],
    ["flag", iconFlag],
    ["function", iconFunction],
    ["golang", iconLangGo],
    ["graphql", iconGraphql],
    ["hammer", iconHammer],
    ["help", iconHelp],
    ["history", iconHistory],
    ["home", iconHome],
    ["index", iconIndex],
    ["info", iconInfo],
    ["integration", iconIntegration],
    ["java", iconLangJava],
    ["javascript", iconLangJavaScript],
    ["key", iconKey],
    ["kotlin", iconLangKotlin],
    ["language", iconConsole],
    ["list", iconList],
    ["live", iconLive],
    ["marker", iconMarker],
    ["mcp", iconMCP],
    ["memory", iconMemory],
    ["model", iconModel],
    ["mojo", iconLangMojo],
    ["namespace", iconNamespace],
    ["package", iconPackageClosed],
    ["php", iconLangPHP],
    ["plugin", iconPlugin],
    ["plus", iconPlus],
    ["python", iconLangPython],
    ["query", iconQuery],
    ["relation", iconRelation],
    ["rust", iconLangRust],
    ["search", iconSearch],
    ["server", iconServer],
    ["sidekick", iconSidekick],
    ["spectron", iconSpectron],
    ["storage", iconDistributedStorage],
    ["support", iconHelp],
    ["surreal", iconSurreal],
    ["surrealist", iconSurrealist],
    ["swift", iconLangSwift],
    ["table", iconTable],
    ["text", iconText],
    ["transfer", iconTransfer],
    ["university", iconUniversity],
    ["variable", iconVariable],
    ["video", iconVideo],
    ["wrench", iconWrench],
] as const);

export const SECTION_ICONS_NAMES = Array.from(SECTION_ICONS.keys());
export type SectionIconName = (typeof SECTION_ICONS_NAMES)[number];
