import type { CategoryItem } from './types';

const categories = [
    'Applications',
    'Client libraries',
    'Management interfaces',
    'Development tools',
    'Deployment tools',
    'Docker images',
    'Integrations',
    'Libraries',
    'GitHub Actions',
    'Starter Kits',
    'Tutorials',
    'Videos',
    'Projects',
    'Embeddings',
];

const michaAuthor = {
    name: 'Micha de Vries',
    role: 'Software Engineer',
};

const karimAuthor = {
    name: 'Karim Lalani',
    role: 'Software Engineer',
};

const sebastianWesselAuthor = {
    name: 'Sebastian Wessel',
    role: 'Software Engineer',
};

const odonnoAuthor = {
    name: 'David Bottiau',
    role: 'Software Engineer',
};

const dataByCategory: Record<string, CategoryItem[]> = {
    Applications: [
        {
            text: 'SurrealDB',
            url: 'https://github.com/surrealdb/surrealdb',
            author: 'surrealdb',
            deploy: 'standard',
            lesson: 'data management',
            difficulty: 'beginner',
        },
    ],
    'Client libraries': [
        {
            text: 'awaited-surrealdb',
            url: 'https://github.com/theopensource-company/awaited-surrealdb',
            author: michaAuthor,
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-cloudflare',
            url: 'https://github.com/theopensource-company/surrealdb-cloudflare',
            author: michaAuthor,
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-erlang',
            url: 'https://github.com/meppu/surreal',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Meppu',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb-flutter',
            url: 'https://github.com/duhanbalci/surrealdb_flutter',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Duhan Balci',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb-spring-client',
            url: 'https://github.com/Mukund2900/surrealdb-spring-client',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Mukund Mundhra',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb.c',
            url: 'https://github.com/surrealdb/surrealdb.c',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.cr',
            url: 'https://github.com/yorci/surrealdb.cr',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Muhammed Yaşar',
                role: 'Backend Crafter',
            },
        },
        {
            text: 'surrealdb.go',
            url: 'https://github.com/surrealdb/surrealdb.go',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.java',
            url: 'https://github.com/surrealdb/surrealdb.java',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.js',
            url: 'https://github.com/surrealdb/surrealdb.js',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.net',
            url: 'https://github.com/surrealdb/surrealdb.net',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.node',
            url: 'https://github.com/surrealdb/surrealdb.node',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.php',
            url: 'https://github.com/surrealdb/surrealdb.php',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.py',
            url: 'https://github.com/surrealdb/surrealdb.py',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'python sdk',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb.wasm',
            url: 'https://github.com/surrealdb/surrealdb.wasm',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb',
            url: 'https://github.com/surrealdb/surrealdb/tree/main/crates/sdk',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'SurrealDB_DSL',
            url: 'https://github.com/mnbjhu/SurrealDB_DSL',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
            author: {
                name: 'Mnbjhu',
                role: 'Software Engineer',
            },
        },
    ],
    'Management interfaces': [
        {
            text: 'SurrealDB Admin',
            url: 'https://github.com/sachinbhutani/surrealdb-admin',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Sachin Bhutani',
                role: 'Software Engineer',
            },
        },
        {
            text: 'SurrealDB Explorer',
            url: 'https://github.com/iDevelopThings/SurrealDB-Explorer',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Sam Parton',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Surrealist',
            url: 'https://github.com/surrealdb/surrealist',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'SurrealReact',
            url: 'https://github.com/rvdende/surrealreact',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Rouan van der Ende',
                role: 'Software Engineer',
            },
        },
    ],
    'Development tools': [
        {
            text: 'surreal-codegen',
            url: 'https://github.com/siteforge-io/surreal-codegen',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Albert Marashi',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb-client-generator',
            url: 'https://github.com/sebastianwessel/surrealdb-client-generator',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: sebastianWesselAuthor,
        },
    ],
    'Deployment tools': [
        {
            text: 'Dokku Surrealdb',
            url: 'https://github.com/IgnisDa/dokku-surrealdb',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Diptesh Choudhuri',
                role: 'Software Engineer',
            },
        },
        {
            text: 'GKE using Terraform',
            url: 'https://github.com/dvanmali/terraform-google-surrealdb',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Dylan Vanmali',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Pterodactyl Egg',
            url: 'https://github.com/Stefanuk12/Pterodactyl/blob/master/eggs/misc/egg-surrealdb.json',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: {
                name: 'Stefan',
                role: 'Freelance Developer',
            },
        },
    ],
    'Docker images': [
        {
            text: 'surrealdb/surrealdb',
            url: 'https://hub.docker.com/r/surrealdb/surrealdb',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
            author: 'surrealdb',
        },
    ],
    Integrations: [
        {
            text: 'Use SurrealDB with LangChain',
            url: 'https://github.com/surrealdb/langchain-surrealdb',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Create and manage AI agent teams',
            url: '/docs/integrations/frameworks/crewai',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Evaluate and improve your AI models',
            url: '/docs/integrations/frameworks/deepeval',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Orchestrate your data pipelines',
            url: '/docs/integrations/frameworks/dagster',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Develop autonomous AI agents',
            url: '/docs/integrations/frameworks/camel',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Build RAG pipelines with SurrealDB as vector store',
            url: '/docs/integrations/frameworks/llama-index',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Build dynamic AI applications',
            url: '/docs/integrations/frameworks/dynamiq',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'Create lightweight AI agents',
            url: '/docs/integrations/frameworks/smolagents',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'ai',
        },
        {
            text: 'SurrealDB Document Loader for LangChain',
            url: 'https://python.langchain.com/docs/integrations/document_loaders/surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
            author: {
                name: 'LangChain',
                role: 'Open Source Project',
            },
        },
        {
            text: 'SurrealDB Vector Store for LangChain',
            url: 'https://python.langchain.com/docs/integrations/vectorstores/surrealdb',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'LangChain',
                role: 'Open Source Project',
            },
        },
    ],
    Libraries: [
        {
            text: 'allographer',
            url: 'https://github.com/itsumura-h/nim-allographer',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Itsumura H.',
                role: 'Software Engineer',
            },
        },
        {
            text: 'kysely-surrealdb',
            url: 'https://github.com/igalklebanov/kysely-surrealdb',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Igal Klebanov',
                role: 'Software Engineer',
            },
        },
        {
            text: 'PySurrealDB',
            url: 'https://github.com/aurelion314/pysurrealdb',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Mike Aurelion',
                role: 'Software Engineer',
            },
        },
        {
            text: 'ra-surrealdb',
            url: 'https://github.com/djedi23/ra-surrealdb',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Moïse Valvassori',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Sirqle',
            url: 'https://github.com/PythiaSocialTech/sirqle',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Tudor Andrei Dumitrascu',
                role: 'Lead AI Developer',
            },
        },
        {
            text: 'surreal-id',
            url: 'https://github.com/liamwh/surreal-id',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Liam Woodleigh-Hardinge',
                role: 'Lead Engineer',
            },
        },
        {
            text: 'surrealdb_extra',
            url: 'https://github.com/jakin010/surrealdb_extra',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Jakin010',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb_migration_engine',
            url: 'https://github.com/mcmah309/surrealdb_migration_engine',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Henry',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb_query_builder',
            url: 'https://github.com/AyushChothe/surrealdb_query_builder',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Ayush Chothe',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb-extras',
            url: 'https://docs.rs/surrealdb-extras/latest/surrealdb_extras/',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Frederik Uni',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealdb-migrations',
            url: 'https://github.com/Odonno/surrealdb-migrations',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: odonnoAuthor,
        },
        {
            text: 'surrealdb-valibot',
            url: 'https://github.com/ShadowWolf308/surrealdb-valibot',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Levy van der Valk',
                role: 'Web Developer',
            },
        },
        {
            text: 'surrealdb-zod',
            url: 'https://github.com/ShadowWolf308/surrealdb-zod',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Levy van der Valk',
                role: 'Web Developer',
            },
        },
        {
            text: 'Surrealised',
            url: 'https://github.com/ozone-team/surrealised',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Harry Carpenter',
                role: 'Software Engineer',
            },
        },
        {
            text: 'surrealist',
            url: 'https://github.com/kotolex/surrealist',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Kotolex',
                role: 'Software Engineer',
            },
        },
        {
            text: 'type-surrealdb',
            url: 'https://github.com/ibilux/type-surrealdb',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Bilux',
                role: 'Software Engineer',
            },
        },
    ],
    'GitHub Actions': [
        {
            text: 'SurrealDB GitHub Action',
            url: 'https://github.com/marketplace/actions/surrealdb-in-github-action',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: 'surrealdb',
        },
        {
            text: 'surrealdb-migrations',
            url: 'https://github.com/marketplace/actions/surrealdb-migrations',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: odonnoAuthor,
        },
        {
            text: 'Use SurrealDB in GitHub Actions',
            url: 'https://github.com/marketplace/actions/use-surrealdb-in-github-actions',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
            author: {
                name: 'Jan Vollmer',
                role: 'Software Engineer',
            },
        },
    ],
    'Starter Kits': [
        {
            text: 'SurrealDB + SpringBoot.',
            url: 'https://github.com/PDROJACK/surrealdb-springboot-starter',
            author: {
                name: 'Priyadarshan Singh',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'Starter Kit for SurrealDB + Tauri + Next.js.',
            url: 'https://github.com/reymom/surrealdb-starter-taurikit',
            author: {
                name: 'Reymon',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + FastAPI-NextJS Starter.',
            url: 'https://github.com/richie-omondi/fastapi-nextjs-surrealdb-starterkit',
            author: {
                name: 'Mardav Chirag and Richard Orido',
                role: 'Software Engineers',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Flask Starter.',
            url: 'https://github.com/syedzubeen/surrealdb_flask_starter_app',
            author: {
                name: 'Syed Zubeen',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Go Driver Starter.',
            url: 'https://github.com/sbshah97/surrealdb-go-starter-project',
            author: {
                name: 'Salman Shah',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Koa starter rest api.',
            url: 'https://github.com/jerempy/surrealdb-starter-koa',
            author: {
                name: 'Jerempy',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Nuxt 3 Starter.',
            url: 'https://github.com/dvanmali/surrealdb-nuxt-starter',
            author: {
                name: 'Dylan Vanmali',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + React-Nodejs starter.',
            url: 'https://github.com/MSaiKiran9/react.nodejs_starter',
            author: {
                name: 'Sai Kiran',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Rocket.',
            url: 'https://github.com/davidzr/surrealdb-rocket-starter',
            author: {
                name: 'David Zabala',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SolidStart Starter.',
            url: 'https://github.com/metruzanca/surreal-solid-template',
            author: {
                name: 'Sam Zanca',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Streamlit Starter.',
            url: 'https://github.com/LuciAkirami/surrealdb-streamlit-starter-kit',
            author: {
                name: 'Lucifer Akirami',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit Auth Example.',
            url: 'https://github.com/AlbertMarashi/surrealdb-svelte-auth-template',
            author: {
                name: 'Albert Marashi',

                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit Starter.',
            url: 'https://github.com/spinspire/surrealdb-sveltekit-starter',
            author: {
                name: 'Jitesh Doshi',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit.',
            url: 'https://github.com/oskar-gmerek/surreal-sveltekit',
            author: {
                name: 'Oskar Gmerek',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Vue Blog Starter.',
            url: 'https://github.com/SrWither/surrealdb-vuejs',
            author: {
                name: 'Fadel SrWither',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Vue Starter.',
            url: 'https://github.com/inkollusireeshaadharani/vue-starter-kit',
            author: {
                name: 'Dharani Inkollu',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
    ],
    Tutorials: [
        {
            text: "Aeon's Surreal Renaissance - Official book for in-depth learning through storytelling.",
            url: '/learn/book',
            author: 'surrealdb',
            difficulty: 'beginner',
            deploy: 'standard',
            lesson: 'data management',
        },
        {
            text: 'Build an AI RAG Agent',
            url: 'https://github.com/colinmcnamara/austin_langchain/blob/main/labs/LangChain_104/104-langgraph-rag-agent.ipynb',
            author: karimAuthor,
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'CLI phone book in Python using SurrealDB as database.',
            url: 'https://code-maven.com/surrealdb-python-cli-phonebook',
            author: {
                name: 'Gabor Szabo',
                role: 'Software Engineer',
            },
            lesson: 'data management',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Getting started with SurrealDB using Python and Docker.',
            url: 'https://code-maven.com/surrealdb-getting-started',
            author: {
                name: 'Gabor Szabo',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            lesson: 'python sdk',
            difficulty: 'beginner',
        },
        {
            text: 'Getting started with SurrealDB.',
            url: '/blog/getting-started-with-surrealdb',
            author: 'surrealdb',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Hosting Surreal DB in Rust in Less Than 3 Minutes.',
            url: 'https://www.youtube.com/watch?v=VoRoeL1tal4',
            author: {
                name: 'Gui Bibeau',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'How to Use SurrealDb with the Fresh Framework and Deno.',
            url: 'https://www.freecodecamp.org/news/how-to-use-surrealdb-with-fresh-framework/',
            author: {
                name: 'Rajdeep Singh',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Improve database management with SurrealDB.',
            url: 'https://blog.logrocket.com/improve-database-management-surrealdb/',
            author: {
                name: 'Alexander Nnakwue',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Simple API with Gin/Gonic and SurrealDB (GO).',
            url: 'https://atoo.hashnode.dev/simple-api-with-gingonic-and-surrealdb',
            author: {
                name: 'Atharva Deshpande',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB - Rust Embedded Database - Quick Tutorial.',
            url: 'https://www.youtube.com/watch?v=iOyvum0D3LM',
            author: {
                name: 'Jeremy Chone',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB Fundamentals Course - Official course to efficiently learn SurrealDB in 3 hours.',
            url: '/learn/fundamentals',
            author: 'surrealdb',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Unlocking SurrealDB: Building a Real-World Multi-Tenant RBAC System Made Easy (4 Part Series).',
            url: 'https://dev.to/sebastian_wessel/series/24535',
            author: sebastianWesselAuthor,
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
    ],
    Videos: [
        {
            text: 'Beyond Surreal? A closer look at NewSQL Relational Data - Beyond Fireship.',
            url: 'https://www.youtube.com/watch?v=LCAIkx1p1k0',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Fireship',
                role: 'Content Creator - Software Engineer',
            },
        },
        {
            text: 'Getting started with SurrealDB! Future of cloud databases (maybe)?',
            url: 'https://www.youtube.com/watch?v=D41jb4DDIdA',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Chris Hay',
                role: 'Content Creator',
            },
        },
        {
            text: 'Livestream series documenting learning SurrealDB.',
            url: 'https://www.youtube.com/playlist?list=PL5AVzKSngnt_xPGNuYdrbB7NZtJbQ046a',
            author: {
                name: 'Xkonti',
                role: 'Content Creator',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: "Rust Powered Database SurrealDB (It's Pretty Ambitious) - Code to the Moon.",
            url: 'https://www.youtube.com/watch?v=DPQbuW9dQ7w',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Code to the Moon',
                role: 'Content Creator',
            },
        },
        {
            text: 'SurrealDB in 100 seconds.',
            url: 'https://www.youtube.com/watch?v=C7WFwgDRStM',
            author: {
                name: 'Fireship',
                role: 'Content Creator',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB. The Kitchen Sink Document Store that might dethrone Firebase.',
            url: 'https://www.youtube.com/watch?v=tWpj8Bc_jBQ',
            author: {
                name: 'Ray Villalobos',
                role: 'Content Creator',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Using SurrealDB to prove football statistics.',
            url: 'https://www.youtube.com/watch?v=6J1SPMXzOh4&t=5s',
            author: {
                name: 'Joseph McCarthy',
                role: 'Content Creator',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
    ],
    Projects: [
        {
            text: 'DOX For Everything - An online forum for discussions, questions and answers, fan pages, blogs, or anything else.',
            url: 'https://github.com/tcm151/dox',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Tyler McKay',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Gofer Engine - An HL7 (Healthcare Level 7) Interface Engine built to deploy on Node.js servers.',
            url: 'https://github.com/gofer-engine/gofer-engine',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Anthony Master',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Kards Social - FOSS social media app.',
            url: 'https://github.com/theopensource-company/kards-social',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: michaAuthor,
        },
        {
            text: 'MECOMP - A local music player that uses surrealdb as the backend.',
            url: 'https://github.com/AnthonyMichaelTDM/mecomp',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Anthony Rubick',
                role: 'Software Engineer',
            },
        },
        {
            text: 'Nextjs + surrealdb demo - Basic blog that serves as a demo / template for your nextjs + surrealdb project.',
            url: 'https://github.com/kearfy/demo-nextjs-surrealdb',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: michaAuthor,
        },
        {
            text: 'Playrbase - Event & player management system.',
            url: 'https://github.com/theopensource-company/playrbase',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: michaAuthor,
        },
        {
            text: 'Style Guide AI Assistant - A voice enabled AI assistant that lets you talk to your wardrobe.',
            url: 'https://github.com/lalanikarim/style-guide-ai-assistant',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
            author: karimAuthor,
        },
        {
            text: 'Surreal-4o Fine-tuned Model Datasets for SurrealQL Queries - Project to create structured datasets for OpenAI.',
            url: 'https://github.com/sFritsch09/surreal-4o',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Sebastian Fritsch',
                role: 'Fullstack Developer',
            },
        },
        {
            text: 'SurrealDB AI Docs Retrieval - Project to showcase: How to build a GPT-Based question-answering system on top of SurrealDB Docs.',
            url: 'https://github.com/truskovskiyk/surrealdb-docs-retrieval',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Kyryl Truskovskyi',
                role: 'Machine Learning Engineer',
            },
        },
        {
            text: 'SurrealDB as a Vector Store for LangChain - A Jupyter notebook demonstrating how to use SurrealDB as a Vector Store.',
            url: 'https://github.com/lalanikarim/notebooks/blob/main/SurrealDB-Langchain.ipynb',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: karimAuthor,
        },
        {
            text: 'SurrealDB Presence Demo - Demo project on how to create a realtime presence web application using SurrealDB Live Queries.',
            url: 'https://github.com/Odonno/surrealdb-presence-demo',
            lesson: ['ingest', 'real-time'],
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'David Bottiau',
                role: 'Software Engineer',
            },
        },
        {
            text: 'SurrealDB Sandbox - An offline browser-based playground for experimenting with SurrealDB.',
            url: 'https://github.com/plasmatech8/surrealdb-sandbox',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Mark Connelly',
                role: 'Software Engineer',
            },
        },
        {
            text: 'SurrealDB x OpenAI - Example of RAG using SurrealDB and OpenAI.',
            url: 'https://github.com/Ce11an/surrealdb-openai',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Cellan Hall',
                role: 'MLOps Engineer',
            },
        },
        {
            text: 'SurrealML vs PyTorch vs ONNX - Benchmarking the performance of SurrealML against PyTorch and ONNX - Vladimir Rotariu.',
            url: 'https://github.com/vladimirrotariu/surrealml-vs-onnx-vs-pytorch/tree/main',
            lesson: 'query performance',
            difficulty: 'advanced',
            deploy: 'standard',
            author: {
                name: 'Vladimir Rotariu',
                role: 'AI & Backend engineer',
            },
        },
    ],
    Embeddings: [
        {
            text: 'Leverage OpenAI’s powerful text embeddings',
            author: 'surrealdb',
            url: '/docs/integrations/embeddings/openai',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: ['embedding', 'ai'],
        },
        {
            text: 'Use AWS Titan embeddings for semantic search',
            author: 'surrealdb',
            url: '/docs/integrations/embeddings/bedrock',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'embedding',
        },
        {
            text: 'Generate embeddings with Google’s Gemini models',
            author: 'surrealdb',
            url: '/docs/integrations/embeddings/gemini',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: ['embedding', 'ai'],
        },
        {
            text: 'Domain-flexible sentence vectors with k-NN search',
            url: '/docs/integrations/embeddings/mixedbreads',
            author: 'surrealdb',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'embedding',
        },
    ],
};

export const examplePageConfig = {
    categories,
    dataByCategory,
};
