import type { CategoryItem } from './types';

const categories = [
    'Applications',
    'Client libraries',
    'Management interfaces',
    'Development tools',
    'Deployment tools',
    'Docker images',
    'Integrations',
    'Libraries',
    'GitHub Actions',
    'Starter Kits',
    'Tutorials',
    'Videos',
    'Projects',
];

const dataByCategory: Record<string, CategoryItem[]> = {
    Applications: [
        {
            text: 'SurrealDB',
            url: 'https://github.com/surrealdb/surrealdb',
            description:
                'SurrealDB is a scalable, distributed, collaborative, document-graph database, for the realtime web.',
            author: {
                name: 'surrealdb',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            lesson: 'data management',
            difficulty: 'beginner',
        },
    ],
    'Client libraries': [
        {
            text: 'awaited-surrealdb',
            url: 'https://github.com/theopensource-company/awaited-surrealdb',
            description:
                'Typescript wrapper for surrealdb.js that holds queries until connection is established.',
            author: {
                name: 'The Open Source Company',
                role: 'Developer Advocate',
                image: '',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-cloudflare',
            url: 'https://github.com/theopensource-company/surrealdb-cloudflare',
            description:
                "A Typescript implementation for SurrealDB's HTTP API. Can also be used outside of Cloudflare.",
            author: {
                name: 'The Open Source Company',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-erlang',
            url: 'https://github.com/meppu/surreal',
            description: 'Client library for Erlang and other BEAM languages.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-flutter',
            url: 'https://github.com/duhanbalci/surrealdb_flutter',
            description: 'Client library for Dart and Flutter.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-spring-client',
            url: 'https://github.com/Mukund2900/surrealdb-spring-client',
            description:
                'An unofficial maven library to easily integrate surrealdb with springboot.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.c',
            url: 'https://github.com/surrealdb/surrealdb.c',
            description: 'Official driver for C.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.cr',
            url: 'https://github.com/yorci/surrealdb.cr',
            description:
                'Client library for Crystal with support for HTTP and WebSocket connections.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.go',
            url: 'https://github.com/surrealdb/surrealdb.go',
            description: 'Official driver for Golang.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.java',
            url: 'https://github.com/surrealdb/surrealdb.java',
            description: 'Official driver for Java.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.js',
            url: 'https://github.com/surrealdb/surrealdb.js',
            description: 'Official driver for JavaScript.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.net',
            url: 'https://github.com/surrealdb/surrealdb.net',
            description: 'Official driver for .NET.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.node',
            url: 'https://github.com/surrealdb/surrealdb.node',
            description: 'Official driver for Node.js.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.php',
            url: 'https://github.com/surrealdb/surrealdb.php',
            description: 'Official driver for PHP.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb.py',
            url: 'https://github.com/surrealdb/surrealdb.py',
            description: 'Official driver for Python.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'python sdk',
        },
        {
            text: 'surrealdb.wasm',
            url: 'https://github.com/surrealdb/surrealdb.wasm',
            description: 'Official driver for WebAssembly.',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb',
            url: 'https://github.com/surrealdb/surrealdb/tree/main/crates/sdk',
            description: 'Official driver for Rust.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB_DSL',
            url: 'https://github.com/mnbjhu/SurrealDB_DSL',
            description: 'An unofficial Kotlin DSL and driver.',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
        },
    ],
    'Management interfaces': [
        {
            text: 'SurrealDB Admin',
            url: 'https://github.com/sachinbhutani/surrealdb-admin',
            description:
                'A serverless app to browse and query your SurrealDB instance.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB Explorer',
            url: 'https://github.com/iDevelopThings/SurrealDB-Explorer',
            description: 'A simple database viewer/editor for SurrealDB.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
        {
            text: 'Surrealist',
            url: 'https://github.com/surrealdb/surrealist',
            description:
                'Official dashboard, query playground and database explorer for SurrealDB.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
        {
            text: 'SurrealReact',
            url: 'https://github.com/rvdende/surrealreact',
            description: 'An explorer UI written in react.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
    ],
    'Development tools': [
        {
            text: 'surreal-codegen',
            url: 'https://github.com/siteforge-io/surreal-codegen',
            description:
                'SurrealDB Typescript type-safe client generator which extends the official SurrealDB package.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-client-generator',
            url: 'https://github.com/sebastianwessel/surrealdb-client-generator',
            description:
                'A handy tool that simplifies the process of generating zod schemas and TypeScript clients.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
    ],
    'Deployment tools': [
        {
            text: 'Dokku Surrealdb',
            url: 'https://github.com/IgnisDa/dokku-surrealdb',
            description: 'A plugin to deploy SurrealDB as a Dokku plugin.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
        {
            text: 'GKE using Terraform',
            url: 'https://github.com/dvanmali/terraform-google-surrealdb',
            description:
                'Multicluster Cross-Regional Deployment using GKE Autopilot and Terraform.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
        {
            text: 'Pterodactyl Egg',
            url: 'https://github.com/Stefanuk12/Pterodactyl/blob/master/eggs/misc/egg-surrealdb.json',
            description:
                'An egg to deploy SurrealDB for the Pterodactyl Panel.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
    ],
    'Docker images': [
        {
            text: 'surrealdb/surrealdb',
            url: 'https://hub.docker.com/r/surrealdb/surrealdb',
            description: 'Official Docker image.',
            deploy: 'standard',
            difficulty: 'advanced',
            lesson: 'integrations',
        },
    ],
    Integrations: [
        {
            text: 'SurrealDB Document Loader for LangChain',
            url: 'https://python.langchain.com/docs/integrations/document_loaders/surrealdb',
            description:
                'A simple document loader implementation around SurrealDB for LangChain.',
            deploy: 'standard',
            difficulty: 'intermediate',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB Vector Store for LangChain',
            url: 'https://python.langchain.com/docs/integrations/vectorstores/surrealdb',
            description:
                'Use SurrealDB as a vector store backed retriever within LangChain to build rich Generative AI applications with Large Language Models.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
    ],
    Libraries: [
        {
            text: 'allographer',
            url: 'https://github.com/itsumura-h/nim-allographer',
            description:
                'A query builder and schema builder for Nim that also supports SurrealDB.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'kysely-surrealdb',
            url: 'https://github.com/igalklebanov/kysely-surrealdb',
            description:
                'Kysely (type-safe sql query builder) dialects, plugins and other goodies for SurrealDB.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'PySurrealDB',
            url: 'https://github.com/aurelion314/pysurrealdb',
            description: 'SurrealDB driver and query builder for Python.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'ra-surrealdb',
            url: 'https://github.com/djedi23/ra-surrealdb',
            description:
                'A data provider and an auth provider for react admin to integrate with SurrealDB.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'Sirqle',
            url: 'https://github.com/PythiaSocialTech/sirqle',
            description: 'Python wrapper for surrealdb.py.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surreal-id',
            url: 'https://github.com/liamwh/surreal-id',
            description:
                'Create custom ID types that are guaranteed to be valid RecordIds in SurrealDB.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb_extra',
            url: 'https://github.com/jakin010/surrealdb_extra',
            description: 'Query builder and orm.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb_migration_engine',
            url: 'https://github.com/mcmah309/surrealdb_migration_engine',
            description: 'Simple yet powerful migration engine for SurrealDB.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb_query_builder',
            url: 'https://github.com/AyushChothe/surrealdb_query_builder',
            description: 'SurrealDB query builder for Dart and Flutter.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-extras',
            url: 'https://docs.rs/surrealdb-extras/latest/surrealdb_extras/',
            description:
                'Creates namespace, database, tables and defines attributes automatically.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-migrations',
            url: 'https://github.com/Odonno/surrealdb-migrations',
            description:
                'An awesome SurrealDB migration tool, with a user-friendly CLI and a versatile Rust library.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-valibot',
            url: 'https://github.com/ShadowWolf308/surrealdb-valibot',
            description:
                "Re-usable valibot schema's for use with the JavaScript SDK.",
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-zod',
            url: 'https://github.com/ShadowWolf308/surrealdb-zod',
            description:
                "Re-usable zod schema's for use with the JavaScript SDK.",
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'Surrealised',
            url: 'https://github.com/ozone-team/surrealised',
            description:
                'A Server-Side TypeScript SurrealDB Client with a fluent query builder.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealist',
            url: 'https://github.com/kotolex/surrealist',
            description:
                'Python synchronous client with support for HTTP and WebSocket connections, and all SurrealDB features.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'type-surrealdb',
            url: 'https://github.com/ibilux/type-surrealdb',
            description:
                'Generate schemas and .surql for SurrealDB using TypeScript classes and decorators.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
    ],
    'GitHub Actions': [
        {
            text: 'SurrealDB GitHub Action',
            url: 'https://github.com/marketplace/actions/surrealdb-in-github-action',
            description:
                'Official GitHub Action to use SurrealDB in GitHub Continuous Integration pipelines.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'surrealdb-migrations',
            url: 'https://github.com/marketplace/actions/surrealdb-migrations',
            description:
                'This GitHub Action installs and runs surrealdb-migrations.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'Use SurrealDB in GitHub Actions',
            url: 'https://github.com/marketplace/actions/use-surrealdb-in-github-actions',
            description: 'GitHub Action for using SurrealDB in your tests.',
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
    ],
    'Starter Kits': [
        {
            text: 'SurrealDB + SpringBoot.',
            url: 'https://github.com/PDROJACK/surrealdb-springboot-starter',
            description: 'Starter Kit for SurrealDB + SpringBoot.',
            author: {
                name: 'PDROJACK',
                role: 'Software Engineer',
                image: '',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'Starter Kit for SurrealDB + Tauri + Next.js.',
            url: 'https://github.com/reymom/surrealdb-starter-taurikit',
            description: 'Starter Kit for SurrealDB + Tauri + Next.js.',
            author: {
                name: 'Reymom',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + FastAPI-NextJS Starter.',
            url: 'https://github.com/richie-omondi/fastapi-nextjs-surrealdb-starterkit',
            description: 'Starter Kit for SurrealDB + FastAPI-NextJS.',
            author: {
                name: 'Mardav Chirag and Richard Orido',
                image: '',
                role: 'Software Engineers',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Flask Starter.',
            url: 'https://github.com/syedzubeen/surrealdb_flask_starter_app',
            description: 'Starter Kit for SurrealDB + Flask.',
            author: {
                name: 'Syed Zubeen',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Go Driver Starter.',
            url: 'https://github.com/sbshah97/surrealdb-go-starter-project',
            description: 'Starter Kit for SurrealDB + Go Driver.',
            author: {
                name: 'Salman Shah',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Koa starter rest api.',
            url: 'https://github.com/jerempy/surrealdb-starter-koa',
            description: 'Starter Kit for SurrealDB + Koa.',
            author: {
                name: 'Jerempy',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Nuxt 3 Starter.',
            url: 'https://github.com/dvanmali/surrealdb-nuxt-starter',
            description: 'Starter Kit for SurrealDB + Nuxt 3.',
            author: {
                name: 'Dylan Vanmali',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + React-Nodejs starter.',
            url: 'https://github.com/MSaiKiran9/react.nodejs_starter',
            description: 'Starter Kit for SurrealDB + React-Nodejs.',
            author: {
                name: 'M SaiKiran',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Rocket.',
            url: 'https://github.com/davidzr/surrealdb-rocket-starter',
            description: 'Starter Kit for SurrealDB + Rocket.',
            author: {
                name: 'David Zabala',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SolidStart Starter.',
            url: 'https://github.com/metruzanca/surreal-solid-template',
            description: 'Starter Kit for SurrealDB + SolidStart.',
            author: {
                name: 'Sam "metru" Zanca',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Streamlit Starter.',
            url: 'https://github.com/LuciAkirami/surrealdb-streamlit-starter-kit',
            description: 'Starter Kit for SurrealDB + Streamlit.',
            author: {
                name: 'Lucifer Akirami',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit Auth Example.',
            url: 'https://github.com/AlbertMarashi/surrealdb-svelte-auth-template',
            description: 'Starter Kit for SurrealDB + SvelteKit Auth Example.',
            author: {
                name: 'Albert Marashi',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit Starter.',
            url: 'https://github.com/spinspire/surrealdb-sveltekit-starter',
            description: 'Starter Kit for SurrealDB + SvelteKit.',
            author: {
                name: 'Jitesh Doshi',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + SvelteKit.',
            url: 'https://github.com/oskar-gmerek/surreal-sveltekit',
            description: 'Starter Kit for SurrealDB + SvelteKit.',
            author: {
                name: 'Oskar Gmerek',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Vue Blog Starter.',
            url: 'https://github.com/SrWither/surrealdb-vuejs',
            description: 'Starter Kit for SurrealDB + Vue Blog Starter.',
            author: {
                name: 'SrWither',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
        {
            text: 'SurrealDB + Vue Starter.',
            url: 'https://github.com/inkollusireeshaadharani/vue-starter-kit',
            description: 'Starter Kit for SurrealDB + Vue Starter.',
            author: {
                name: 'Dharani Inkollu',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            difficulty: 'beginner',
            lesson: 'integrations',
        },
    ],
    Tutorials: [
        {
            text: "Aeon's Surreal Renaissance - Official book for in-depth learning through storytelling.",
            url: '/learn/book',
            description:
                'Official book for in-depth learning through storytelling.',
            author: {
                name: 'SurrealDB',
                image: '',
                role: 'Software Engineer',
            },
            difficulty: 'beginner',
            deploy: 'standard',
            lesson: 'data management',
        },
        {
            text: 'Build an AI RAG Agent',
            url: 'https://github.com/colinmcnamara/austin_langchain/blob/main/labs/LangChain_104/104-langgraph-rag-agent.ipynb',
            description:
                'Build an AI RAG Agent with LangGraph, Ollama, Llama2, and SurrealDB.',
            author: {
                name: 'Karim Lalani',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'CLI phone book in Python using SurrealDB as database.',
            url: 'https://code-maven.com/surrealdb-python-cli-phonebook',
            description:
                'CLI phone book in Python using SurrealDB as database.',
            author: {
                name: 'Gabor Szabo',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'data management',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Getting started with SurrealDB using Python and Docker.',
            url: 'https://code-maven.com/surrealdb-getting-started',
            author: {
                name: 'Gabor Szabo',
                image: '',
                role: 'Software Engineer',
            },
            deploy: 'standard',
            lesson: 'python sdk',
            difficulty: 'beginner',
        },
        {
            text: 'Getting started with SurrealDB.',
            url: '/blog/getting-started-with-surrealdb',
            author: {
                name: 'SurrealDB',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Hosting Surreal DB in Rust in Less Than 3 Minutes.',
            url: 'https://www.youtube.com/watch?v=VoRoeL1tal4',
            author: {
                name: 'Gui Bibeau',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'How to Use SurrealDb with the Fresh Framework and Deno.',
            url: 'https://www.freecodecamp.org/news/how-to-use-surrealdb-with-fresh-framework/',
            author: {
                name: 'Rajdeep Singh',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Improve database management with SurrealDB.',
            url: 'https://blog.logrocket.com/improve-database-management-surrealdb/',
            author: {
                name: 'Alexander Nnakwue',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Simple API with Gin/Gonic and SurrealDB (GO).',
            url: 'https://atoo.hashnode.dev/simple-api-with-gingonic-and-surrealdb',
            author: {
                name: 'Atharva Deshpande',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB - Rust Embedded Database - Quick Tutorial.',
            url: 'https://www.youtube.com/watch?v=iOyvum0D3LM',
            author: {
                name: 'Jeremy Chone',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB Fundamentals Course - Official course to efficiently learn SurrealDB in 3 hours.',
            url: '/learn/fundamentals',
            author: {
                name: 'SurrealDB',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Unlocking SurrealDB: Building a Real-World Multi-Tenant RBAC System Made Easy (4 Part Series).',
            url: 'https://dev.to/sebastian_wessel/series/24535',
            author: {
                name: 'Sebastian Wessel',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
    ],
    Videos: [
        {
            text: 'Beyond Surreal? A closer look at NewSQL Relational Data - Beyond Fireship.',
            url: 'https://www.youtube.com/watch?v=LCAIkx1p1k0',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Getting started with SurrealDB! Future of cloud databases (maybe)?',
            url: 'https://www.youtube.com/watch?v=D41jb4DDIdA',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Livestream series documenting learning SurrealDB.',
            url: 'https://www.youtube.com/playlist?list=PL5AVzKSngnt_xPGNuYdrbB7NZtJbQ046a',
            author: {
                name: 'Xkonti',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: "Rust Powered Database SurrealDB (It's Pretty Ambitious) - Code to the Moon.",
            url: 'https://www.youtube.com/watch?v=DPQbuW9dQ7w',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB in 100 seconds.',
            url: 'https://www.youtube.com/watch?v=C7WFwgDRStM',
            author: {
                name: 'Fireship',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB. The Kitchen Sink Document Store that might dethrone Firebase.',
            url: 'https://www.youtube.com/watch?v=tWpj8Bc_jBQ',
            author: {
                name: 'Ray Villalobos',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Using SurrealDB to prove football statistics.',
            url: 'https://www.youtube.com/watch?v=6J1SPMXzOh4&t=5s',
            author: {
                name: 'Joseph McCarthy',
                image: '',
                role: 'Software Engineer',
            },
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
    ],
    Projects: [
        {
            text: 'DOX For Everything - An online forum for discussions, questions and answers, fan pages, blogs, or anything else.',
            url: 'https://github.com/tcm151/dox',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Gofer Engine - An HL7 (Healthcare Level 7) Interface Engine built to deploy on Node.js servers.',
            url: 'https://github.com/gofer-engine/gofer-engine',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Kards Social - FOSS social media app.',
            url: 'https://github.com/theopensource-company/kards-social',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'MECOMP - A local music player that uses surrealdb as the backend.',
            url: 'https://github.com/AnthonyMichaelTDM/mecomp',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Nextjs + surrealdb demo - Basic blog that serves as a demo / template for your nextjs + surrealdb project.',
            url: 'https://github.com/kearfy/demo-nextjs-surrealdb',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Playrbase - Event & player management system.',
            url: 'https://github.com/theopensource-company/playrbase',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Style Guide AI Assistant - A voice enabled AI assistant that lets you talk to your wardrobe.',
            url: 'https://github.com/lalanikarim/style-guide-ai-assistant',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'Surreal-4o Fine-tuned Model Datasets for SurrealQL Queries - Project to create structured datasets for OpenAI.',
            url: 'https://github.com/sFritsch09/surreal-4o',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB AI Docs Retrieval - Project to showcase: How to build a GPT-Based question-answering system on top of SurrealDB Docs.',
            url: 'https://github.com/truskovskiyk/surrealdb-docs-retrieval',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB as a Vector Store for LangChain - A Jupyter notebook demonstrating how to use SurrealDB as a Vector Store.',
            url: 'https://github.com/lalanikarim/notebooks/blob/main/SurrealDB-Langchain.ipynb',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB Presence Demo - Demo project on how to create a realtime presence web application using SurrealDB Live Queries.',
            url: 'https://github.com/Odonno/surrealdb-presence-demo',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB Sandbox - An offline browser-based playground for experimenting with SurrealDB.',
            url: 'https://github.com/plasmatech8/surrealdb-sandbox',
            lesson: 'ingest',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealDB x OpenAI - Example of RAG using SurrealDB and OpenAI.',
            url: 'https://github.com/Ce11an/surrealdb-openai',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
        {
            text: 'SurrealML vs PyTorch vs ONNX - Benchmarking the performance of SurrealML against PyTorch and ONNX - Vladimir Rotariu.',
            url: 'https://github.com/vladimirrotariu/surrealml-vs-onnx-vs-pytorch/tree/main',
            lesson: 'ai',
            difficulty: 'advanced',
            deploy: 'standard',
        },
    ],
};

export const examplePageConfig = {
    categories,
    dataByCategory,
};
