name: CI

on: push

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Checkout sourcecode
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Checking Code Quality
        run: bun run quality:check

  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Checkout sourcecode
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build docs
        run: bun run build
